@Library('ultra-lib@1.3.1') _

pipelineService(
  helm: [ subChartName: 'client', ],
  images: [
    [name: 'client-management', extraBuildArgs: "WORKSPACE_NAME=management", filename: 'clientDockerfile']
  ],
)