@Library('ultra-lib@1.3.1') _

pipelineService(
  helm: [ subChartName: 'apiGateway', ],
  images: [
    [name: 'forms-api-gateway', extraBuildArgs: "WORKSPACE_NAME=forms", filename: 'serverDockerfile']
  ],
)
