import type { ThemeColors } from '@/themes/types';

const base = {
  background: '#FFFFFF',
  mainTitle: '#343F58',
  questionText: '#A2A7B2',
  active: '#FF9C8F',
  buttonHoverBackground: '#EBEBEE',
  genericBackground: '#F7F7F7',
};

export const colors: ThemeColors = {
  global: {
    background: base.background,
  },
  header: {
    background: base.background,
    mainTitle: '#16104D',
    subTitle: '#565188',
    systemNote: 'rgba(0, 0, 0, 0.7)',
  },
  milestone: {
    background: 'linear-gradient(129.23deg, #69D9FB -18.36%, #6D4EEB 138.79%)',
  },
  milestoneSection: {
    selectedSectionBackground: '#ffffff1a',
    completedSectionNumber: '#FFFFFF70',
    notStartedSectionNumber: '#FFFFFF4D',
    completedSectionTitle: '#FFFFFFBA',
    notStartedSectionTitle: '#FFFFFF73',
    progressAxisAfterAnswer: base.background,
    selectedSectionNumber: '#F3F3FFCF',
    selectedSectionTitle: base.background,
    progressAxisBeforeAnswer: '#416CD7',
  },
  openingText: {
    background: base.background,
    mainTitle: '#23418A',
    text: base.mainTitle,
    footerText: 'rgba(52, 63, 88, 0.6)',
    boxShadow: 'rgba(0, 0, 0, 0.1)',
  },
  sectionHeader: {
    background: 'linear-gradient(136.77deg, #69D9FB, #6D4EEB)',
    mainTitle: base.background,
  },

  mainQuestion: {
    mainTitle: base.mainTitle,
    text: base.questionText,
  },
  subQuestionNumbers: {
    title: base.mainTitle,
    numbers: base.mainTitle,
    buttonGroupBackground: '#F1F1F2',
    labelsColor: '#ABB3C6',
    dividerColor: '#98A6BA',
    indexColor: '#6F7D93',
    buttonBackground: base.background,
    buttonSelectedBackground: base.active,
    buttonHoverBackground: base.buttonHoverBackground,
  },
  subQuestionFreeText: {
    background: base.background,
    freeTextBackground: base.genericBackground,
    selectedBorder: base.active,
    title: base.mainTitle,
    subTitle: base.mainTitle,
    textBeforeAnswer: '#909AB0',
    textAfterAnswer: base.mainTitle,
    borderColor: '#d8d8d8',
    inputBorderColor: '#f7f7f7',
    boxShadow: 'rgba(0, 0, 0, 0.1)',
  },
  subQuestionChoices: {
    background: base.background,
    buttonBackground: base.genericBackground,
    buttonBackgroundHover: base.buttonHoverBackground,
    buttonSelectedBorder: base.active,
    title: base.mainTitle,
    subTitle: base.mainTitle,
    possibleAnswers: base.questionText,
    buttonRegularText: '#7A859F',
    textAfterAnswer: base.mainTitle,
    boxShadow: 'rgba(0, 0, 0, 0.15)',
  },
  button: {
    background: 'linear-gradient(90deg, #416CD7 0%, #6D76F0 100%)',
    color: base.background,
  },
  surveyHeader: {
    mainTitle: '#23418A',
    subTitle: '#7284AB',
    divider: '#7284AB',
  },
  backgroundQuestionsHeader: {
    backgroundTitle:
      'linear-gradient(136.77deg, #69D9FB -17.79%, #6D4EEB 137.8%)',
    partTitle: base.background,
    boxShadow: 'rgba(110, 110, 110, 0.17)',
    backgroundSection: 'rgba(255, 255, 255, 0.5)',
    backgroundColor: 'rgba(255, 255, 255, 0.27)',
    iconShadow: 'rgba(0, 0, 0, 0.13)',
  },
  backgroundQuestions: {
    iconPersonBackground: base.genericBackground,
    iconPersonBorder: '#F0EFEB',
    iconSelectedField: '#5271FF',
    dropdownToggleIcon: '#BFBFC0',
    dropdownBackground: base.background,
    dropdownBorder: '#F1F2F2',
    dropdownActiveBorder: '#5271FF',
    dropdownShadow: '#0000000d',
    dropdownSeparator: '#e5e5e6',
    toggleSelectedBackground: base.background,
    toggleBackground: base.genericBackground,
    toggleSelectedBoxShadow: 'rgba(16, 24, 40, 0.06)',
    toggleDividerColor: '#E5E5E6',
    menuHoverBackground: base.genericBackground,
    textTitle: base.mainTitle,
    fieldBackground: '#F8F9FB',
    fieldTitle: base.questionText,
    fieldText: base.mainTitle,
    dropdownText: '#9FA1BF',
    dropdownActiveText: base.mainTitle,
    menuText: base.mainTitle,
    menuActiveText: base.mainTitle,
    toggleSelected: base.mainTitle,
    toggleNotSelected: '#7B8292',
  },
  footer: {
    background: base.background,
    buttonSaveActiveBackground: '#5975FC',
    buttonCancelBackground: base.background,
    buttonCancelBorder: '#475C85',
    mainOrCancelText: '#1C376E',
    subText: '#475C85',
    confirmButtonText: base.background,
    boxShadow: 'rgba(0, 0, 0, 0.1)',
    closeIcon: '#a5a5a7',
    actionsBoxShadow: 'rgba(16, 24, 40, 0.1)',
  },
};
