export const SERVICE_NAME = 'SERVICE_NAME';
export const ULTRA_CLIENT_PROXY_OPTIONS = 'ULTRA_CLIENT_PROXY_OPTIONS';
export const SENDER_SERVICE_NAME = 'SENDER_SERVICE_NAME';
export const CLIENT_PROXY_SERVICE_TOKEN = 'OCP';
