name: Validate CI Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate-ci-checks:
    uses: ClickIDF/ultra-infrastructures/.github/workflows/validate-ci-checks.yaml@v2