@Library('ultra-lib@1.3.1') _

pipelineService(
  helm: [ subChartName: 'authorization', ],
  images: [
    [name: 'authorization', extraBuildArgs: "WORKSPACE_NAME=management", filename: 'serverDockerfile']
  ],
)